---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: mixed-line-ending
    - id: check-byte-order-marker
    - id: check-executables-have-shebangs
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-yaml
      files: .*\.(yaml|yml)$
      args:
      - "--allow-multiple-documents"
      - "--unsafe"
    - id: debug-statements
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
  - repo: https://github.com/ansible-community/ansible-lint
    rev: v5.3.2
    hooks:
    - id: ansible-lint
      additional_dependencies:
      - ansible-core
      - yamllint
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.6
    hooks:
    - id: shellcheck
