---
- name: check
  become: true
  hosts: all
  tasks:
  - name: "Run ZFS check"
    ansible.builtin.shell: |
      set -o pipefail
      lsmod | grep '^zfs'
    args:
      executable: /usr/bin/bash
    tags:
    - skip_ansible_lint
