---
# Notes
# * drives     -- An array of devices.
# * subvolumes -- A hash of logical volumes to be created under a given VG, with each volume
#                 key additional configuration can be defined. If no additional configuration
#                 is needed the key can be used with an empty hash or null.
# * layout     -- drive layout: raid0, raid10, single
#
# btrfs_pools:
#   pool0:
#     layout: raid10
#     mount_options:
#     - noatime
#     - space_cache=v2
#     - compress=lzo
#     drives:
#     - "/dev/nvme1n1"
#     - "/dev/nvme2n1"
#     - "/dev/nvme3n1"
#     - "/dev/nvme4n1"
#     subvolumes:
#       snapshots: /home/solana/snapshots
#       ledger: /home/solana/ledger
#       account: /home/solana/account
