---
# NOTE(cloudnull): This task file will run three checks to see if the target RAID array exists.
#                  This tripleo check is done to ensure we're not damaging data and the role
#                  remains idempotent.

- name: Check status of array
  ansible.builtin.command: >-
    grep "^{{ outer_item.key }}" /proc/mdstat
  register: "array_check"
  changed_when: false
  failed_when: false
  check_mode: false

- name: Check array config
  ansible.builtin.command: >-
    grep "^ARRAY.*{{ outer_item.key }}" /etc/mdadm/mdadm.conf
  register: "config_check"
  changed_when: false
  failed_when: false
  check_mode: false

- name: Create array block
  become: true
  when:
  - array_check.rc != 0
  - config_check.rc != 0
  block:
  - name: Creating array
    ansible.builtin.shell: >-
      yes | mdadm
      --create
      --assume-clean
      --level={{ outer_item.value.level }}
      --chunk={{ outer_item.value.chunk | default(256) }}
      --raid-devices={{ outer_item.value.drives | count }}
      /dev/{{ outer_item.key }}
      {{ outer_item.value.drives | join (' ') }}
    args:
      creates: "/dev/{{ outer_item.key }}"
    register: "array_created"
    tags:
    - skip_ansible_lint

  - name: Set update initramfs fact
    ansible.builtin.set_fact:
      _mdadm_update_initramfs: true
    when:
    - array_created is changed
