---
- name: Full posix example
  become: true
  hosts: all
  vars:
    test_mdadm_arrays:
      md0:
        drives:
        - "/dev/sdb"
        - "/dev/sdc"
        level: "raid0"
    test_volume_groups:
      pool0:
        drives:
        - "/dev/md0"
        logical_volumes:
          lv0:
            size: 1G
    test_drives:
      - filesystem: xfs
        device: /dev/pool0/lv0
        mountpoint: /mnt/lv0
  tasks:
    - include_role:
        name: cloudnull.filesystems.mdadm
      vars:
        mdadm_arrays: "{{ test_mdadm_arrays }}"
    - include_role:
        name: cloudnull.filesystems.lvg
      vars:
        volume_groups: "{{ test_volume_groups }}"
    - include_role:
        name: cloudnull.filesystems.format
      vars:
        format_filesystem: "{{ item.filesystem }}"
        format_device: "{{ item.device }}"
        format_mount_point: "{{ item.mountpoint }}"
      loop: "{{ test_drives }}"
