---
- name: Create a volume group
  community.general.lvg:
    vg: "{{ _vg_name }}"
    pvs: "{{ _vg_drives | join(',') }}"
    pesize: 32M

- name: Create logical volumes
  community.general.lvol:
    vg: "{{ _vg_name }}"
    lv: "{{ item.key }}"
    size: "{{ item.value.size }}"
    opts: "{{ item.value.opts | default(omit) }}"
  loop: "{{ _vg_logical_volumes | dict2items }}"
