---
- name: Instantiate volume group
  become: true
  block:
  - name: Run pool interaction
    ansible.builtin.include_tasks: _lv.yml
    loop: "{{ volume_groups | dict2items }}"
    loop_control:
      loop_var: _lv_item
      label: "{{ _lv_item.key }}"
    vars:
      _vg_name: "{{ _lv_item.key }}"
      _vg_drives: "{{ _lv_item.value.drives }}"
      _vg_logical_volumes: "{{ _lv_item.value.logical_volumes | default({}) }}"
