name: Run pull-request molecule job for mdadm
on:
  pull_request:
    paths:
    - 'roles/mdadm/*'
    - 'roles/mdadm/defaults/*'
    - 'roles/mdadm/meta/*'
    - 'roles/mdadm/tasks/*'
    - 'roles/mdadm/vars/*'
jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
        - 2drive-raid0
        - 4drive-raid10
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install ansible-core
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install --upgrade ansible-core molecule
    - name: Install current collection
      run: ansible-galaxy collection install . --upgrade
    - name: Run molecule
      run: |
        cd roles/mdadm
        molecule --debug --base-config ../../molecule/molecule-base.yml test --scenario-name ${{ matrix.scenario }}
