name: Run pull-request molecule job for lvg
on:
  pull_request:
    paths:
    - 'roles/lvg/*'
    - 'roles/lvg/defaults/*'
    - 'roles/lvg/meta/*'
    - 'roles/lvg/tasks/*'
jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
        - 1drive
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install ansible-core
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install --upgrade ansible-core molecule
    - name: Install current collection
      run: ansible-galaxy collection install . --upgrade
    - name: Run molecule
      run: |
        cd roles/lvg
        molecule --debug --base-config ../../molecule/molecule-base.yml test --scenario-name ${{ matrix.scenario }}
