name: Run pull-request molecule job for zfs_setup
on:
  pull_request:
    paths:
    - 'roles/zfs_setup/*'
    - 'roles/zfs_setup/defaults/*'
    - 'roles/zfs_setup/handlers/*'
    - 'roles/zfs_setup/meta/*'
    - 'roles/zfs_setup/tasks/*'
    - 'roles/zfs_setup/templates/*'
    - 'roles/zfs_setup/vars/*'
jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
        - default
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install ansible-core
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install --upgrade ansible-core molecule
    - name: Install current collection
      run: ansible-galaxy collection install . --upgrade
    - name: Run molecule
      run: |
        cd roles/zfs_setup
        molecule --debug --base-config ../../molecule/molecule-base.yml test --scenario-name ${{ matrix.scenario }}
