name: Run pull-request molecule job for zfs_setup
on:
  pull_request:
    paths:
    - 'roles/zfs_setup/*'
jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
        - default
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install ansible-core
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install --upgrade ansible-core
    - name: Install current collection
      run: ansible-galaxy collection install . --upgrade
    - name: Molecule run
      uses: gofrolist/molecule-action@v2
      with:
        molecule_options: --debug
        molecule_command: test
        molecule_args: >-
          --scenario-name "${{ matrix.scenario }}"
          --base-config "${GITHUB_WORKSPACE}/molecule/molecule-base.yaml"
        molecule_working_dir: "${GITHUB_WORKSPACE}/roles/zfs_setup"
