---

- name: Create a new tmux session
  command: "tmux new-session -d -s '{{ zfs_filesystem }}@{{ zfs_target_host }}'"
  failed_when: false

# tasks file for zfs_send, loop used to send in a nested tmux command.
- name: Initiate ZFS Send / Recv
  become: true
  shell: "tmux send-keys '{{ item }} && exit' C-m"
  loop:
  - zfs send {{ zfs_pool }}/{{ zfs_filesystem }} |
    mbuffer -q -s 128k -m 1G |
    ssh {{ zfs_replicate_ssh_options }} {{ ansible_user }}@{{ hostvars[zfs_target_host]["ansible_host"] }}
    "mbuffer -s 128k -m 1G | zfs receive -s -F {{ zfs_pool }}/{{ zfs_filesystem }}"
